language: python
python: 2.7
sudo: false
cache: pip
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
install:
- pip install tox coveralls
script:
- tox -e $TOX_ENV
after_success:
  coveralls
notifications:
  email: false
